<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AutoHellevator</AssemblyName>
    <RootNamespace>AutoHellevator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TerrariaServer">
      <HintPath>TerrariaServer.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TShockAPI">
      <HintPath>TShockAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
